### ISSUE TITLE
Package your app with flutter_distributor.

### ISSUE THREAD

**Issue by lijy91** [JerryFans/TinyPNG4Flutter#1]
[flutter_distributor](https://github.com/leanflutter/flutter_distributor) It is a packaging and publishing tool specially developed for flutter. Can it be used for packaging in this project?

**Comment by JerryFans** [comment]
I will have a try to the next version and reply you later

**Comment by JerryFans** [comment]
If i want to publish a linux version which packages should i use.

**Comment by lijy91** [comment]
可以查看文档：https://distributor.leanflutter.org/v/zh/
> Linux 的支持还在开发中。可以暂时按照这个示例进行配置 https://github.com/leanflutter/flutter_distributor/tree/main/examples/hello_world/linux/packaging/deb

**Comment by JerryFans** [comment]
Nice ! 已经用上了
